# Generated by Django 4.2 on 2023-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_image_task_alter_task_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Urgent and important', 'Urgent and important'), ('Not urgent but important', 'Not urgent but important'), ('Urgent but not important', 'Urgent but not important'), ('Not urgent and not important', 'Not urgent and not important')], default='Urgent and important', max_length=50, verbose_name='task category'),
        ),
    ]
